services:
  app:
    image: node:alpine
    restart: always
    container_name: comparador-lp-react
    command: [sh, -c, "npm install && npm run dev -- --host"]
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 3000:3000
