services:
  app:
    image: node:alpine
    restart: always
    container_name: comparador-lp-app
    command: [sh, -c, 'su node -c "npm install && npm run dev"']
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 1234:1234

  build:
    image: node:alpine
    container_name: comparador-lp-build
    command: [sh, -c, 'su node -c "npm install && npm run build"']
    volumes:
      - .:/code
    working_dir: /code
